### ISSUE TITLE
fails to fetch data, trim command?!

### ISSUE THREAD

**Issue by ryan-c-dev** [carterprince/libby#1]
try to do as in video preview:
libby nineteen-eighty-four

What I get in both zsh or bash:
```
/usr/bin/libby: line 25: [:missing `]'
fetching data...
/usr/bin/libby: line 45: trim: command not found
No results found for 'nineteen eighty-four'
```
not aware of this 'trim' command, can't be four in AUR or regular repositories(note: Using Artix Linux but includes standard Arch repos)

Also tried with single quotes, to no avail:
`libby 'nineteen eighty-four'`

but no luck!

**Comment by carterprince** [comment]
Ah sorry, `trim` is a command I keep in `~/.local/bin` for convenience. It simply pipes stdin into `awk '{$1=$1};1'`. Will fix

**Comment by carterprince** [comment]
Also fixed the other bug where the closing `]` wasn't separated with a space. Should be able to `git pull`
or just re-clone the repo
