### ISSUE TITLE
Libby can't find the "trim" command on Ubuntu 22.04

### ISSUE THREAD

**Issue by corinroyal** [carterprince/libby#2]
I've installed Libby using the git clone method on Ubuntu. I've also installed the requirements. When running Libby I get the following error: 

`/usr/bin/libby: line 45: trim: command not found`

I can't figure out what this "trim" command is, or where to find it.  Neither an "apt search trim" or Google search were helpful. 

Where can I get "trim"? 

Thanks for any help you can provide and thank you for this awesome tool.

**Comment by carterprince** [comment]
This was fixed ~10 minutes ago. Update/reinstall libby!

In case you are curious: `trim` is a utility I keep in `~/.local/bin` for my own convenience. It just removes duplicate and trailing whitespace. Didn't think to remove it, but it's fixed now.
