### ISSUE TITLE
[FR] Use ANSI colors for book info

### ISSUE THREAD

**Issue by murlakatamenka** [carterprince/libby#6]
Since fzf has `--ansi` flag it'll be good for book information to be color-coded, i.e. title in one color, author in another, publisher, size, year, format etc.
Will improve legibility / readability for long lines like:

![image](https://user-images.githubusercontent.com/7361274/180667312-5cd8e299-68ad-435a-a1df-99d907f869d3.png)

**Comment by carterprince** [comment]
I agree, this would be good to add. Will do, stay tuned

**Comment by carterprince** [comment]
Added in 1d30163ca0489404f975d75ab50f7c214e6942b5.

**Comment by carterprince** [comment]
Here's how it looks btw:
![image](https://user-images.githubusercontent.com/11081492/180698709-6730e650-5050-45c5-bdb3-1e6e07179578.png)

**Comment by murlakatamenka** [comment]
Awesome, isn't it? Thanks!

Last minor issue I see is that separator for multiple publishers should be made white.
